name: Simple Flagging Workflow

on:
  workflow_dispatch:

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Configure Git Settings
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "GitHub Actions"

    - name: Update submodule and fetch the specific file
      run: |
        git submodule update --init --recursive
        cd aphis-inspection-reports
        git fetch origin
        git checkout origin/main -- data/combined/inspections-citations.csv

    - name: Extract new rows
      id: generate_timestamped_new_rows_file
      run: |
        source venv/bin/activate
        cd scripts
        python extract_new_rows.py
        OUTPUT_PATH=$(tail -n 1 output.log | sed -n 's/Generated file path: //p')
        echo "::set-output name=output_path::$OUTPUT_PATH"

    - name: Debug file paths
      run: ls -R ${{ github.workspace }}/data/

    - name: Flag extreme temperatures
      run: |
        source venv/bin/activate
        cd scripts
        python flag_extreme_temperatures.py

    - name: Flag air transportation issues
      run: |
        source venv/bin/activate
        cd scripts
        python flag_air_transport.py

    - name: Append new rows for air transport
      run: |
        source venv/bin/activate
        cd scripts
        python append_new_rows.py \
          --original_file_path ${{ github.workspace }}/data/output/air_transport/inspections_citations_with_air_transport_flags.csv \
          --new_rows_file_path ${{ github.workspace }}/data/flagging_process/air_transport/initial_flagged.csv \
          --combined_file_path ${{ github.workspace }}/data/output/air_transport/inspections_citations_with_air_transport_flags.csv

    - name: Append new rows for extreme temperatures
      run: |
        source venv/bin/activate
        cd scripts
        python append_new_rows.py \
          --original_file_path ${{ github.workspace }}/data/output/extreme_temperatures/inspections_citations_with_extreme_temperatures_flags.csv \
          --new_rows_file_path ${{ github.workspace }}/data/flagging_process/extreme_temperatures/initial_flagged.csv \
          --combined_file_path ${{ github.workspace }}/data/output/extreme_temperatures/inspections_citations_with_extreme_temperatures_flags.csv

    - name: Append new rows for inspections_citations
      run: |
        source venv/bin/activate
        cd scripts
        python append_new_rows.py \
          --original_file_path ${{ github.workspace }}/data/output/inspections_citations_latest.csv \
          --new_rows_file_path ${{ steps.generate_timestamped_new_rows_file.outputs.output_path }} \
          --combined_file_path ${{ github.workspace }}/data/output/inspections_citations_latest.csv

