name: Simple Flagging Workflow

on: 
  workflow_dispatch:

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'  # This ensures submodules are checked out

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Specify the Python version you need

    - name: Install dependencies
      run: pip install --user -r requirements.txt  # Ensure all dependencies are listed here
      
    - name: Configure Git Pull Behavior
      run: git config pull.rebase false  # Explicitly set pull behavior to avoid divergence issues

    - name: Update submodule
      run: |
        git submodule update --init --recursive
        cd data/raw/aphis-inspection-reports
        git pull origin main

    - name: Ensure the specific file is updated
      run: |
        cd data/raw/aphis-inspection-reports/data/combined
        git fetch --all
        git checkout origin/main -- inspections-citations.csv

    - name: Extract new rows
      run: python .scripts/extract_new_rows.py 

    - name: Flag extreme temperatures
      run: python .scripts/flag_extreme_temperatures.py 

    - name: Flag air transportation issues
      run: python .scripts/flag_air_transport.py 

    - name: Append flagged rows
      run: python .scripts/append_flagged_rows.py
