name: Simple Flagging Workflow

on: 
  workflow_dispatch:

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv  # Create a virtual environment
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Configure Git Pull Behavior
      run: git config pull.rebase false

    - name: Set Git Committer Identity
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "GitHub Actions"

    - name: Update submodule and pull the specific file
      run: |
        git submodule update --init --recursive  # Ensure the submodule is initialized and updated
        cd aphis-inspection-reports  # Go into the submodule directory
        git fetch origin  # Fetch latest updates from the remote repository
        git checkout origin/main -- data/combined/inspections-citations.csv  # Checkout the specific file

    - name: Ensure the specific file is updated
      run: |
        cd aphis-inspection-reports/data/combined
        git fetch --all  # Fetch all changes
        git checkout origin/main -- inspections-citations.csv  # Ensure file is from the remote

    - name: Extract new rows
      run: |
        source venv/bin/activate  # Ensure the virtual environment is activated
        cd scripts
        python extract_new_rows.py

    - name: Flag extreme temperatures
      run: |
        source venv/bin/activate  # Ensure the virtual environment is activated
        cd scripts
        python flag_extreme_temperatures.py

    - name: Flag air transportation issues
      run: |
        source venv/bin/activate  # Ensure the virtual environment is activated
        cd scripts
        python flag_air_transport.py

    - name: Append new rows
      run: |
        source venv/bin/activate  # Ensure the virtual environment is activated
        cd scripts
        python append_new_rows.py
